// export const NEW_PROFILE = "NEW_PROFILE";
// export const RETRIEVE_SITE = "RETRIEVE_SITE";
// export const RETRIEVE_CABINET = "RETRIEVE_CABINET";
// export const RETRIEVE_ENTERPRISE = "RETRIEVE_ENTERPRISE";
// export const RETRIEVE_SMTP = "RETRIEVE_SMTP";
// export const RETRIEVE_KEY = "RETRIEVE_KEY";
// export const FETCH_KEY = "FETCH_KEY";
// export const DELETE_KEY = "DELETE_KEY";
// export const FETCH_ROLE = "FETCH_ROLE";
// export const RETRIEVE_ROLE = "RETRIEVE_ROLE";
// export const DELETE_ROLE = "DELETE_ROLE";
// export const RETRIEVE_USER = "RETRIEVE_USER";
// export const FETCH_USER = "FETCH_USER";
// export const DELETE_USER = "DELETE_USER";
// export const RETRIEVE_ACTIVITY = "RETRIEVE_ACTIVITY";
// export const FETCH_ACTIVITY = "FETCH_ACTIVITY";
// export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
// export const NEW_ACTIVITY = "NEW_ACTIVITY";
// export const FETCH_EVENT = "FETCH_EVENT";
// export const RETRIEVE_EVENT = "RETRIEVE_EVENT";
// export const DELETE_EVENT = "DELETE_EVENT";
// export const FETCH_EXCEPTION = "FETCH_EXCEPTION";
// export const RETRIEVE_EXCEPTION = "RETRIEVE_EXCEPTION";
// export const DELETE_EXCEPTION = "DELETE_EXCEPTION";
// export const FETCH_EVENTLOGS = "FETCH_EVENTLOGS";
// export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
// export const RETRIEVE_NOTIFICATION = "RETRIEVE_NOTIFICATION";
// export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const FETCH_TOP_USERS = "FETCH_TOP_USERS";
export const FETCH_TOP_KEYS = "FETCH_TOP_KEYS";
// export const ACKNOWLEDGE_EVENTLOGS = "ACKNOWLEDGE_EVENTLOGS";
// export const RETRIEVE_PEG = "RETRIEVE_PEG";
// export const UPDATE_ED = "UPDATE_ED";
// export const UNACKNOWLEDGE_COUNT = "UNACKNOWLEDGE_COUNT";

//Auth 
export const AUTH_LOGIN = "AUTH_LOGIN";
export const UPDATE_LOGIN_ATTEMPTS = "UPDATE_LOGIN_ATTEMPTS";
export const CAPTCHA_VALUE = "CAPTCHA_VALUE";

// role access and manage
export const CREATEROLE = "CREATEROLE";
export const GETROLE = "GETROLE";
export const UPDATEROLE = "UPDATEROLE";
export const DELETEROLE = "DELETEROLE";
// Portal User 
export const CREATE_PORTAL_USER = "CREATE_PORTAL_USER";
export const GET_PORTAL_USER = "GET_PORTAL_USER";
export const DELETE_PORTAL_USER = "DELETE_PORTAL_USER";
export const UPDATE_PROTAL_USER = "UPDATE_PROTAL_USER";
export const UPDATE_LAST_LOGIN = "UPDATE_LAST_LOGIN";

//SMTP
export const CREATE_SMTP = "CREATE_SMTP";

//SMTP and firmawre
export const CREATE_FIRMWARE = "CREATE_FIRMWARE";
export const GET_OTA = "GET_OTA";
export const UPDATE_FIRMWARE = "UPDATE_FIRMWARE";





export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


//State List
export const CREATE_STATE_LIST = "CREATE_STATE_LIST";
export const DELETE_STATE_LIST = "DELETE_STATE_LIST";
export const GET_STATE_LIST = "GET_STATE_LIST";
export const UPDATE_STATE_LIST = "UPDATE_STATE_LIST";

//Ro List
export const CREATE_RO_LIST = "CREATE_RO_LIST";
export const DELETE_RO_LIST = "DELETE_RO_LIST";
export const GET_RO_LIST = "GET_RO_LIST";
export const UPDATE_RO_LIST = "UPDATE_RO_LIST";

//Ams Cabinet
export const CREATE_AMS_CABINET = "CREATE_AMS_CABINET";
export const DELETE_AMS_CABINET = "DELETE_AMS_CABINET";
export const GET_AMS_CABINET = "GET_AMS_CABINET";
export const UPDATE_AMS_CABINET = "UPDATE_AMS_CABINET";

//Key List
export const CREATE_KEY_LIST = "CREATE_KEY_LIST";
export const DELETE_KEY_LIST = "DELETE_KEY_LIST";
export const GET_KEY_LIST = "GET_KEY_LIST";
export const UPDATE_KEY_LIST = "UPDATE_KEY_LIST";

//Activity List
export const CREATE_ACTIVITY_LIST = "CREATE_ACTIVITY_LIST";
export const DELETE_ACTIVITY_LIST = "DELETE_ACTIVITY_LIST";
export const GET_ACTIVITY_LIST = "GET_ACTIVITY_LIST";
export const UPDATE_ACTIVITY_LIST = "UPDATE_ACTIVITY_LIST";

//Event Types
export const CREATE_EVENT_TYPES = "CREATE_EVENT_TYPES";
export const DELETE_EVENT_TYPES = "DELETE_EVENT_TYPES";
export const GET_EVENT_TYPES = "GET_EVENT_TYPES";
export const UPDATE_EVENT_TYPES = "UPDATE_EVENT_TYPES";

//AMS DASHBOARD
export const GET_ZONE = "GET_ZONE";
export const GET_STATE = "GET_STATE";
export const GET_STATE_CODE = "GET_STATE_CODE";
export const GET_RO = "GET_RO";
export const GET_EVENT = "GET_EVENT";
export const GET_ALL_EVENT = "GET_ALL_EVENT";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_ALL_ACTIVITY = "GET_ALL_ACTIVITY";
export const GET_USERRELATEDDATA = "GET_USERRELATEDDATA";
export const GET_LOGIN_ACTIVITY = "GET_LOGIN_ACTIVITY";

//AMS Config

export const GET_SITE_INFORMATION = "GET_SITE_INFORMATION";
export const UPDATE_SITE_INFORMATION = "UPDATE_SITE_INFORMATION";
export const GET_CABINET_OVERVIEW = "GET_CABINET_OVERVIEW";
export const UPDATE_CABINET_OVERVIEW = "UPDATE_SITE_INFORMATION";
export const GET_MANAGE_ROLES_FORM = "GET_MANAGE_ROLES_FORM";
export const UPDATE_MANAGE_ROLES_FORM = "UPDATE_MANAGE_ROLES_FORM";
export const GET_MANAGE_EVENTS_FORM = "GET_MANAGE_EVENTS_FORM";
export const UPDATE_MANAGE_EVENTS_FORM = "UPDATE_MANAGE_EVENTS_FORM";
export const CREATE_MANAGE_EVENT_FORM = "CREATE_MANAGE_EVENT_FORM";
export const DELETE_MANAGE_EVENT_FORM = "DELETE_MANAGE_EVENT_FORM";
export const GET_MANAGE_KEYS_FORM = "GET_MANAGE_KEYS_FORM";
export const UPDATE_MANAGE_KEYS_FORM = "UPDATE_MANAGE_KEYS_FORM";
export const GET_MANAGE_USERS_FORM = "GET_MANAGE_USERS_FORM";
export const CREATE_MANAGE_USERS_FORM = "CREATE_MANAGE_USERS_FORM";
export const UPDATE_MANAGE_USERS_FORM = "UPDATE_MANAGE_USERS_FORM";
export const GET_MANAGE_ACTIVITIES_FORM = "GET_MANAGE_ACTIVITIES_FORM";
export const UPDATE_MANAGE_ACTIVITIES_FORM = "UPDATE_MANAGE_ACTIVITIES_FORM";
export const AMS_CONFIGURATION_SIDEBAR = "AMS_CONFIGURATION_SIDEBAR";
export const SEARCH_SIDEBAR = "SEARCH_SIDEBAR";
export const AMS_CONFIGURATION_SIDEBAR_SELECTED_RO = "AMS_CONFIGURATION_SIDEBAR_SELECTED_RO";



//dashboard ui

export const GET_AMSCABINETSTATUS = "GET_AMSCABINETSTATUS";
export const GET_OFFLINESITES = "GET_OFFLINESITES";
export const GET_DONUTCHART = "GET_DONUTCHART";
export const GET_ZEROEVENTS = "GET_ZEROEVENTS";
export const GET_ZEROACTIVITY = "GET_ZEROACTIVITY";
export const GET_UNAURTHORIZE_EVENT_SITE = "GET_UNAURTHORIZE_EVENT_SITE";
export const GET_UNAURTHORIZE_EVENT_SITE_POPUP = "GET_UNAURTHORIZE_EVENT_SITE_POPUP";
export const GET_EMERGENCY = "GET_EMERGENCY";
export const GET_EMERGENCY_POPUP = "GET_EMERGENCY_POPUP";
export const GET_TOPKEY = "GET_TOPKEY";
export const GET_ZEROPOPUP = "GET_ZEROPOPUP";
export const GET_UNREGISTERED_POPUP = "GET_UNREGISTERED_POPUP";
export const GET_ONLINE_SITES = "GET_ONLINE_SITES";
export const GET_OFFLINE_SITES = "GET_OFFLINE_SITES";
export const GET_TOTAL_SITES = "GET_TOTAL_SITES";
export const GET_USERWITHROCODE = "GET_USERWITHROCODE";
export const GET_EVENT_SITE = "GET_EVENT_SITE";
export const GET_EVENT_SITE_POPUP = "GET_EVENT_SITE_POPUP";
export const GET_ACTIVITY_SITE = "GET_ACTIVITY_SITE";
export const GET_ACTIVTIY_SITE_POPUP = "GET_ACTIVTIY_SITE_POPUP";
export const GET_ZEROEVENT_SITE_POPUP = "GET_ZEROEVENT_SITE_POPUP";
export const GET_ZEROACTIVITY_SITE_POPUP = "GET_ZEROACTIVITY_SITE_POPUP";
export const GET_ACCESS_LIST = "GET_ACCESS_LIST";
export const GET_PINACCESS_POPUP = "GET_PINACCESS_POPUP";
export const GET_BIOACCESS_POPUP = "GET_BIOACCESS_POPUP";
export const GET_WEBACCESS_POPUP = "GET_WEBACCESS_POPUP";
export const GET_PINPLUSWEBACCESS_POPUP = "GET_PINPLUSWEBACCESS_POPUP";
export const GET_NOBOX_POPUP = "GET_NOBOX_POPUP";
export const GET_NOACTIVITY_BOX = "GET_NOACTIVITY_BOX";
export const GET_TOTALEVENT_DESC = "GET_TOTALEVENT_DESC";
export const GET_TOTALEVENTTYPE_DESC = "GET_TOTALEVENTTYPE_DESC";
export const GET_TESTACT_COUNT = "GET_TESTACT_COUNT";
export const GET_TESTACT_POPUP = "GET_TESTACT_POPUP";
export const GET_NOTESTACT_POPUP = "GET_NOTESTACT_POPUP";
export const GET_KEYSBYACT = "GET_KEYSBYACT";
export const GET_BATTERY = "GET_BATTERY";
export const CLEAR_CAPTCHA_VALUE = "CLEAR_CAPTCHA_VALUE";

//access rights
export const GET_MOULES = "GET_MOULES";
export const CREATE_ACCESS = "CREATE_ACCESS";
export const FIND_ACCESS = "FIND_ACCESS";
export const CHECK_ACCESS = "CHECK_ACCESS";